apiVersion: rbac.authorization.k8s.io/v1
kind: ServiceAccount
metadata:
  name: devops-engineer
  namespace: home-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ServiceAccount
metadata:
  name: infrastructure-operator
  namespace: home-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ServiceAccount
metadata:
  name: security-operator
  namespace: home-namespace